import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        canvas: "var(--page-background)",
        card: "var(--surface-primary)",
        elevated: "var(--surface-elevated)",
        muted: "var(--surface-muted)",
        foreground: "var(--text-primary)",
        "secondary-foreground": "var(--text-secondary)",
        "muted-foreground": "var(--text-muted)",
        "disabled-foreground": "var(--text-disabled)",
        link: "var(--text-link)",
        eyebrow: "var(--text-eyebrow)",
        inverse: "var(--text-inverse)",
        border: "var(--border-default)",
        "border-strong": "var(--border-strong)",
        neutral: {
          50: "var(--color-neutral-50)",
          100: "var(--color-neutral-100)",
          200: "var(--color-neutral-200)",
          300: "var(--color-neutral-300)",
          400: "var(--color-neutral-400)",
          500: "var(--color-neutral-500)",
          600: "var(--color-neutral-600)",
          700: "var(--color-neutral-700)",
          800: "var(--color-neutral-800)",
          900: "var(--color-neutral-900)",
          950: "var(--color-neutral-950)",
        },
        purple: {
          50: "var(--color-purple-50)",
          100: "var(--color-purple-100)",
          200: "var(--color-purple-200)",
          300: "var(--color-purple-300)",
          400: "var(--color-purple-400)",
          500: "var(--color-purple-500)",
          600: "var(--color-purple-600)",
          700: "var(--color-purple-700)",
          800: "var(--color-purple-800)",
          900: "var(--color-purple-900)",
        },
        blue: {
          50: "var(--color-blue-50)",
          200: "var(--color-blue-200)",
          600: "var(--color-blue-600)",
          700: "var(--color-blue-700)",
          800: "var(--color-blue-800)",
          900: "var(--color-blue-900)",
          950: "var(--color-blue-950)",
        },
        emerald: {
          50: "var(--color-success-50)",
          200: "var(--color-success-200)",
          600: "var(--color-success-600)",
          700: "var(--color-success-700)",
          800: "var(--color-success-800)",
        },
        amber: {
          50: "var(--color-warning-50)",
          200: "var(--color-warning-200)",
          500: "var(--color-warning-500)",
          700: "var(--color-warning-700)",
          800: "var(--color-warning-800)",
          900: "var(--color-warning-900)",
        },
        red: {
          50: "var(--color-danger-50)",
          100: "var(--color-danger-100)",
          200: "var(--color-danger-200)",
          300: "var(--color-danger-300)",
          600: "var(--color-danger-600)",
          700: "var(--color-danger-700)",
          800: "var(--color-danger-800)",
          900: "var(--color-danger-900)",
        },
      },
      boxShadow: {
        panel: "0 1px 2px rgb(7 21 34 / 0.05)",
      },
    },
  },
  plugins: [],
} satisfies Config;
