"""Domain model package."""

from app.models.ai_governance import ModelPromotionAudit, TrainingJob
from app.models.ai_monitoring import ModelReferenceProfileEntity, PredictionEventEntity
from app.models.ai_retraining import (
    ModelRetrainingAudit,
    ModelRetrainingPolicy,
    ModelRetrainingRequest,
)
from app.models.automl import AutoMLExecutionSlot, AutoMLStudy, AutoMLTrial
from app.models.billing import (
    BillingAuditEvent,
    BillingPlan,
    BillingWebhookEvent,
    InvoiceReference,
    Payment,
    PaymentProviderCustomer,
    PlanEntitlement,
    Subscription,
    UsageCounter,
)
from app.models.datasets import (
    Dataset,
    DatasetUsageReference,
    DatasetVersion,
    DocumentChunk,
    DocumentRecord,
)
from app.models.demo_experience import (
    DataImport,
    DataImportStatus,
    DemoScenarioRun,
    DemoScenarioStatus,
    FactoryLayout,
    ReportJob,
    ReportSchedule,
    ReportStatus,
)
from app.models.email import EmailDeliveryStatus, EmailMessageType, OutboundEmailMessage
from app.models.manufacturing import Company, Factory, Machine
from app.models.mlops import (
    Experiment,
    ModelArtifact,
    TrainingRun,
    TrainingRunStatus,
)
from app.models.monitoring_orchestration import (
    ModelMonitoringEvaluationEntity,
    MonitoringAlertEntity,
    MonitoringJobLockEntity,
    PredictionOutcomeEntity,
)
from app.models.operations import (
    MaintenanceFeedback,
    OperationalAction,
    OperationalActionPriority,
    OperationalActionStatus,
    OperationalNote,
    OperationalTimelineEvent,
    ShiftHandover,
    ShiftStatus,
)
from app.models.pilot import MachineRiskAssessment, ModelFeatureSchema
from app.models.rag import (
    RAGChunkEmbedding,
    RAGConversation,
    RAGIndexBuild,
    RAGIndexedChunk,
    RAGKnowledgeBase,
    RAGKnowledgeBaseDatasetVersion,
    RAGMessage,
    RAGMessageCitation,
)
from app.models.sensor import Sensor
from app.models.sensor_data import (
    ReadingQuality,
    ReadingSource,
    SensorReading,
    UploadJob,
    UploadJobStatus,
)
from app.models.support import SupportRequest, SupportRequestStatus
from app.models.user import (
    AuditEvent,
    EmailVerificationToken,
    PasswordResetToken,
    RefreshToken,
    User,
    UserRole,
)

__all__ = [
    "AutoMLExecutionSlot",
    "AutoMLStudy",
    "AutoMLTrial",
    "AuditEvent",
    "BillingAuditEvent",
    "BillingPlan",
    "BillingWebhookEvent",
    "Company",
    "Dataset",
    "DatasetUsageReference",
    "DatasetVersion",
    "DataImport",
    "DataImportStatus",
    "DemoScenarioRun",
    "DemoScenarioStatus",
    "DocumentChunk",
    "DocumentRecord",
    "EmailDeliveryStatus",
    "EmailMessageType",
    "EmailVerificationToken",
    "Experiment",
    "Factory",
    "FactoryLayout",
    "InvoiceReference",
    "Machine",
    "MachineRiskAssessment",
    "ModelPromotionAudit",
    "ModelReferenceProfileEntity",
    "ModelMonitoringEvaluationEntity",
    "ModelRetrainingAudit",
    "ModelRetrainingPolicy",
    "ModelRetrainingRequest",
    "ModelArtifact",
    "ModelFeatureSchema",
    "MaintenanceFeedback",
    "MonitoringAlertEntity",
    "MonitoringJobLockEntity",
    "OperationalAction",
    "OperationalActionPriority",
    "OperationalActionStatus",
    "OperationalNote",
    "OperationalTimelineEvent",
    "OutboundEmailMessage",
    "Payment",
    "PaymentProviderCustomer",
    "PlanEntitlement",
    "ReadingQuality",
    "ReadingSource",
    "ReportJob",
    "ReportSchedule",
    "ReportStatus",
    "RAGChunkEmbedding",
    "RAGConversation",
    "RAGIndexBuild",
    "RAGIndexedChunk",
    "RAGKnowledgeBase",
    "RAGKnowledgeBaseDatasetVersion",
    "RAGMessage",
    "RAGMessageCitation",
    "RefreshToken",
    "PasswordResetToken",
    "PredictionEventEntity",
    "PredictionOutcomeEntity",
    "Sensor",
    "SensorReading",
    "ShiftHandover",
    "ShiftStatus",
    "SupportRequest",
    "SupportRequestStatus",
    "Subscription",
    "TrainingRun",
    "TrainingRunStatus",
    "TrainingJob",
    "UploadJob",
    "UploadJobStatus",
    "UsageCounter",
    "User",
    "UserRole",
]
